def poiEmails():
    email_list = {"kenneth_lay@enron.net":"LAY KENNETH L",    
            "kenneth_lay@enron.com":"LAY KENNETH L",
            "klay.enron@enron.com":"LAY KENNETH L",
            "kenneth.lay@enron.com":"LAY KENNETH L", 
            "klay@enron.com":"LAY KENNETH L",
            "layk@enron.com":"LAY KENNETH L",
            "chairman.ken@enron.com":"LAY KENNETH L",
            "jeffreyskilling@yahoo.com":"SKILLING JEFFREY K",
            "jeff_skilling@enron.com":"SKILLING JEFFREY K",
            "jskilling@enron.com":"SKILLING JEFFREY K",
            "jeffrey.skilling@enron.com":"SKILLING JEFFREY K",
            "skilling@enron.com":"SKILLING JEFFREY K",
            "jeffrey.k.skilling@enron.com":"SKILLING JEFFREY K",
            "jeff.skilling@enron.com":"SKILLING JEFFREY K",
            #"kevin_a_howard.enronxgate.enron@enron.net":"",
            #"kevin.howard@enron.com":"",
            #"kevin.howard@enron.net":"",
            #"kevin.howard@gcm.com":"",
            #"michael.krautz@enron.com":"",
            "scott.yeager@enron.com":"YEAGER F SCOTT",
            "syeager@fyi-net.com":"YEAGER F SCOTT",
            "scott_yeager@enron.net":"YEAGER F SCOTT",
            "syeager@flash.net":"YEAGER F SCOTT",
            "joe'.'hirko@enron.com":"HIRKO JOSEPH", 
            "joe.hirko@enron.com":"HIRKO JOSEPH", 
            "rex.shelby@enron.com":"SHELBY REX", 
            "rex.shelby@enron.nt":"SHELBY REX", 
            "rex_shelby@enron.net":"SHELBY REX",
            #"jbrown@enron.com":"",
            #"james.brown@enron.com":"", 
            "rick.causey@enron.com":"CAUSEY RICHARD A", 
            "richard.causey@enron.com":"CAUSEY RICHARD A", 
            "rcausey@enron.com":"CAUSEY RICHARD A",
            "calger@enron.com":"CALGER CHRISTOPHER F",
            "chris.calger@enron.com":"CALGER CHRISTOPHER F", 
            "christopher.calger@enron.com":"CALGER CHRISTOPHER F", 
            "ccalger@enron.com":"CALGER CHRISTOPHER F",
            #"tim_despain.enronxgate.enron@enron.net":"", 
            #"tim.despain@enron.com":"",
            "kevin_hannon@enron.com":"HANNON KEVIN P", 
            "kevin'.'hannon@enron.com":"HANNON KEVIN P", 
            "kevin_hannon@enron.net":"HANNON KEVIN P", 
            "kevin.hannon@enron.com":"HANNON KEVIN P",
            "mkoenig@enron.com":"KOENIG MARK E", 
            "mark.koenig@enron.com":"KOENIG MARK E",
            #"m..forney@enron.com":"",
            "ken'.'rice@enron.com":"RICE KENNETH D", 
            "ken.rice@enron.com":"RICE KENNETH D",
            "ken_rice@enron.com":"RICE KENNETH D", 
            "ken_rice@enron.net":"RICE KENNETH D",
            "paula.rieker@enron.com":"RIEKER PAULA H",
            "prieker@enron.com":"RIEKER PAULA H", 
            "andrew.fastow@enron.com":"FASTOW ANDREW S", 
            "lfastow@pdq.net":"FASTOW ANDREW S", 
            "andrew.s.fastow@enron.com":"FASTOW ANDREW S", 
            "lfastow@pop.pdq.net":"FASTOW ANDREW S", 
            "andy.fastow@enron.com":"FASTOW ANDREW S",
            "david.w.delainey@enron.com":"DELAINEY DAVID W", 
            "delainey.dave@enron.com":"DELAINEY DAVID W", 
            "'delainey@enron.com":"DELAINEY DAVID W", 
            "david.delainey@enron.com":"DELAINEY DAVID W", 
            "'david.delainey'@enron.com":"DELAINEY DAVID W", 
            "dave.delainey@enron.com":"DELAINEY DAVID W", 
            "delainey'.'david@enron.com":"DELAINEY DAVID W",
            "ben.glisan@enron.com":"GLISAN JR BEN F", 
            "bglisan@enron.com":"GLISAN JR BEN F", 
            "ben_f_glisan@enron.com":"GLISAN JR BEN F", 
            "ben'.'glisan@enron.com":"GLISAN JR BEN F",
            #"jeff.richter@enron.com":"", 
            #"jrichter@nwlink.com":"",
            #"lawrencelawyer@aol.com":"", 
            #"lawyer'.'larry@enron.com":"", 
            #"larry_lawyer@enron.com":"", 
            #"llawyer@enron.com":"", 
            #"larry.lawyer@enron.com":"", 
            #"lawrence.lawyer@enron.com":"",
            "tbelden@enron.com":"BELDEN TIMOTHY N", 
            "tim.belden@enron.com":"BELDEN TIMOTHY N", 
            "tim_belden@pgn.com":"BELDEN TIMOTHY N", 
            "tbelden@ect.enron.com":"BELDEN TIMOTHY N",
            "michael.kopper@enron.com":"KOPPER MICHAEL J",
            #"dave.duncan@enron.com":"", 
            #"dave.duncan@cipco.org":"", 
            #"duncan.dave@enron.com":"",
            "ray.bowen@enron.com":"BOWEN JR RAYMOND M", 
            "raymond.bowen@enron.com":"BOWEN JR RAYMOND M", 
            "'bowen@enron.com":"BOWEN JR RAYMOND M",
            "wes.colwell@enron.com":"COLWELL WESLEY",
            #"dan.boyle@enron.com":"",
            #"cloehr@enron.com":"", 
            #"chris.loehr@enron.com":""
        }
    return email_list
